/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Catherin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //Centrar FOrmulario
        this.setLocationRelativeTo(null);
        //Arrancar maximizado
        this.setExtendedState(MAXIMIZED_BOTH);
        //Indicar el icono para la aplicación
        this.setIconImage(new ImageIcon(ClassLoader.getSystemResource("com/img/Ventas.png")).getImage());
        this.setTitle("SISTEMA DE COMPRA Y VENTA - 111 MIL PROGRAMADORES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnVentas = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        Referenciales = new javax.swing.JMenu();
        Clientes = new javax.swing.JMenuItem();
        Proveedores = new javax.swing.JMenuItem();
        Articulos = new javax.swing.JMenuItem();
        TipoArt = new javax.swing.JMenuItem();
        Funcionarios = new javax.swing.JMenuItem();
        Transacciones = new javax.swing.JMenu();
        Ventas = new javax.swing.JMenuItem();
        Compras = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        Ayuda = new javax.swing.JMenu();
        Acerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Ventas.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setFocusable(false);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentas);

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Compras.png"))); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.setFocusable(false);
        btnCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCompras);

        Archivo.setText("Archivo");

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/cerrar_15.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        jMenuBar1.add(Archivo);

        Referenciales.setText("Referenciales");

        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        Referenciales.add(Clientes);

        Proveedores.setText("Proveedores");
        Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresActionPerformed(evt);
            }
        });
        Referenciales.add(Proveedores);

        Articulos.setText("Artículos");
        Articulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArticulosActionPerformed(evt);
            }
        });
        Referenciales.add(Articulos);

        TipoArt.setText("Tipo de Artículos");
        TipoArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoArtActionPerformed(evt);
            }
        });
        Referenciales.add(TipoArt);

        Funcionarios.setText("Funcionarios");
        Funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionariosActionPerformed(evt);
            }
        });
        Referenciales.add(Funcionarios);

        jMenuBar1.add(Referenciales);

        Transacciones.setText("Transacciones");

        Ventas.setText("Ventas");
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });
        Transacciones.add(Ventas);

        Compras.setText("Compras");
        Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprasActionPerformed(evt);
            }
        });
        Transacciones.add(Compras);

        jMenuBar1.add(Transacciones);

        Reportes.setText("Reportes");
        jMenuBar1.add(Reportes);

        Ayuda.setText("Ayuda");

        Acerca.setText("Acerca de");
        Acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaActionPerformed(evt);
            }
        });
        Ayuda.add(Acerca);

        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoArtActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        llamarCliente();
    }//GEN-LAST:event_ClientesActionPerformed

    private void ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedoresActionPerformed
        llamarProveedor();
    }//GEN-LAST:event_ProveedoresActionPerformed

    private void ArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArticulosActionPerformed
        llamarArticulo();
    }//GEN-LAST:event_ArticulosActionPerformed

    private void FuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionariosActionPerformed
        llamarFuncionario();
    }//GEN-LAST:event_FuncionariosActionPerformed

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
        llamarVentas();
    }//GEN-LAST:event_VentasActionPerformed

    private void ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprasActionPerformed
        llamarCompras();
    }//GEN-LAST:event_ComprasActionPerformed

    private void AcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaActionPerformed
        JOptionPane.showMessageDialog(this, "SISTEMA DE COMPRA Y VENTA \n111 MIL PROGRAMADORES", "Acerca del Programa", 
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AcercaActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        llamarVentas();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        llamarCompras();
    }//GEN-LAST:event_btnComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if("Windows".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acerca;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem Articulos;
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenuItem Compras;
    private javax.swing.JMenuItem Funcionarios;
    private javax.swing.JMenuItem Proveedores;
    private javax.swing.JMenu Referenciales;
    private javax.swing.JMenu Reportes;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem TipoArt;
    private javax.swing.JMenu Transacciones;
    private javax.swing.JMenuItem Ventas;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnVentas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
    private void llamarVentas(){
        //Creamos una instancia del formulario VentaApp en este caso.
        //Se le pasan dos parámetros (this, true), el primero indica el formulario padre, en este caso "Principal".
        //El segundo si es modal o no.
        VentaApp v = new VentaApp(this, true);
        //Indicamos que se muestren las opciones "minimizar", "maximizar" y "cerrar"
        v.setDefaultCloseOperation(HIDE_ON_CLOSE);
        //Indicamos el título del formulario.
        v.setTitle("Formulario de Ventas");
        //La hacemos visible.
        v.setVisible(true);                
    }
    //Los pasos para llamar cada formulario son iguales al anterior.
    private void llamarCompras(){
        CompraApp c = new CompraApp(this, true);
        c.setDefaultCloseOperation(HIDE_ON_CLOSE);
        c.setTitle("Formulario de Compras");
        c.setVisible(true);                
    }
    
    private void llamarTipo(){
        TipoApp t = new TipoApp(this, true);
        t.setDefaultCloseOperation(HIDE_ON_CLOSE);
        t.setTitle("Formulario de Tipos de Artículos");
        t.setVisible(true);                
    }
    
    private void llamarArticulo(){
        ArticuloApp a = new ArticuloApp(this, true);
        a.setDefaultCloseOperation(HIDE_ON_CLOSE);
        a.setTitle("Formulario de Artículos");
        a.setVisible(true);                
    }
    
    private void llamarCliente(){
        ClienteApp cl = new ClienteApp(this, true);
        cl.setDefaultCloseOperation(HIDE_ON_CLOSE);
        cl.setTitle("Formulario de Clientes");
        cl.setVisible(true);                
    }
    
    private void llamarFuncionario(){
        FuncionarioApp f = new FuncionarioApp(this, true);
        f.setDefaultCloseOperation(HIDE_ON_CLOSE);
        f.setTitle("Formulario de Funcionarios");
        f.setVisible(true);                
    }
    
    private void llamarProveedor(){
        ProveedorApp p = new ProveedorApp(this, true);
        p.setDefaultCloseOperation(HIDE_ON_CLOSE);
        p.setTitle("Formulario de Proveedores");
        p.setVisible(true);                
    }

}
